find_path(GLEW_INCLUDE_DIR GL/glew.h PATHS c:/glew/include)
find_library(GLEW_LIBRARY GLEW PATHS c:/glew/lib)
find_library(GLEW_LIBRARY glew32s PATHS c:/glew/lib)
find_library(GLEW_LIBRARY glew32 PATHS c:/glew/lib)

if(GLEW_INCLUDE_DIR AND GLEW_LIBRARY)
    set(GLEW_INCLUDE_DIRS ${GLEW_INCLUDE_DIR})
    set(GLEW_LIBRARIES ${GLEW_LIBRARY})
endif(GLEW_INCLUDE_DIR AND GLEW_LIBRARY)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(Glew DEFAULT_MSG GLEW_INCLUDE_DIRS GLEW_LIBRARIES)
