GRACE_FLAGS = -DGRACE_NODES_TEX -DGRACE_SPHERES_TEX -DNDEBUG
MGPU_DIR = $(HOME)/moderngpu/

GENCODE_20 = -gencode arch=compute_20,code=sm_20
GENCODE_21 = -gencode arch=compute_21,code=sm_21
GENCODE_30 = -gencode arch=compute_30,code=sm_30
GENCODE_35 = -gencode arch=compute_35,code=sm_35

# Include from above as appropriate.
CUARCH = $(GENCODE_20) $(GENCODE_30)

CXX = g++
CXXFLAGS =
INCLUDES = -I./ -I$(HOME)/local/include/
LFLAGS = -L$(HOME)/local/lib
LIBS = -lgmp -lgmpxx
DEPS= interval.h quadratic.h intersection.cuh Makefile

NVCC = nvcc
# Ensure float/double calculations obey IEEE binary32/64 rules, rather than
# being computed by the x87 FPU.
NVCCFLAGS = $(CUARCH) $(GRACE_FLAGS) -Xcompiler "-fopenmp -mfpmath=sse -msse2"
NVCCINCLUDES = -I$(MGPU_DIR)/include/ $(INCLUDES)
NVCCLFLAGS = -L$(HOME)/local/cuda/lib64 $(LFLAGS)
NVCCLIBS = -lcurand $(LIBS)
NVCCDEPS = $(wildcard ../../kernels/*.cuh) $(wildcard ../../*.*h) $(DEPS)


all: sphere_intersection

%.o: %.cpp $(DEPS)
	$(CXX) $(CXXFLAGS) $(INCLUDES) -c $< -o $@

%.o: %.cu $(NVCCDEPS)
	$(NVCC) $(NVCCFLAGS) $(NVCCINCLUDES) -c $< -o $@

sphere_intersection: sphere_intersection.o interval.o intersection.o
	$(NVCC) $(NVCCFLAGS) $(NVCCINCLUDES) $^ -o $@ $(NVCCLFLAGS) $(NVCCLIBS)


.PHONY: clean

clean:
	-rm -f *.o

distclean: clean
	-rm -f sphere_intersection
